baseURL = 'https://bluearctic.top/'
languageCode = 'en-us'
title = 'BlueArctic'
theme = 'ananke'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# 2. 社交链接 (会显示在每个页面底部)
[params]
  github = "https://github.com/LAJ-THU"

# 2. 关键配置：允许 HTML 渲染（必须放在这里）
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "BlueArctic"  # 左上角显示的网站名(建议短一点)
    weight = 1
    contentDir = "content/en"

    [[languages.en.menu.main]]
      name = "About Me"
      url = "/en/about/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Projects"
      url = "/en/projects/"
      weight = 20
    [[languages.en.menu.main]]
      name = "AI4S Literature"
      url = "/en/literature/"
      weight = 30
    [[languages.en.menu.main]]
      name = "AI4S Tutorial"
      url = "/en/tutorial/"
      weight = 40
    [[languages.en.menu.main]]
      name = "My Whisper"
      url = "/en/whisper/"
      weight = 50

  # --- 中文版设置 ---
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    title = "蓝极" 
    weight = 2
    contentDir = "content/zh"
    
    # 中文菜单 (对应上面的5个，但显示中文)
    [[languages.zh.menu.main]]
      name = "我是谁"
      url = "/zh/about/"
      weight = 10
    [[languages.zh.menu.main]]
      name = "我做过什么"
      url = "/zh/projects/"
      weight = 20
    [[languages.zh.menu.main]]
      name = "文献解读"
      url = "/zh/literature/"
      weight = 30
    [[languages.zh.menu.main]]
      name = "AI4S 教程"
      url = "/zh/tutorial/"
      weight = 40
    [[languages.zh.menu.main]]
      name = "蓝极呢喃"
      url = "/zh/whisper/"
      weight = 50

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "keywords"
    weight = 80

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[[languages.zh.menu.main]]
  name = "搜索"
  url = "/zh/search/"
  weight = 5